name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ["darwin-amd64", "darwin-arm64", "freebsd-386", "freebsd-amd64", "linux-386", "linux-amd64", "linux-arm", "linux-arm64", "windows-386", "windows-amd64",]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix build "#terraform-provider-zone-${{ matrix.platform }}" -L
  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix flake check -L
