name: ci

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix build "#terraform-provider-zone" -L
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix build "#terraform-provider-zone" -L
  check:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix build "#checks.x86_64-linux.ci" -L
